"""
This type stub file was generated by pyright.
"""

from asgiref.typing import ASGI2Application, ASGIReceiveCallable, ASGISendCallable, Scope

class ASGI2Middleware:
    def __init__(self, app: ASGI2Application) -> None:
        ...
    
    async def __call__(self, scope: Scope, receive: ASGIReceiveCallable, send: ASGISendCallable) -> None:
        ...
    


