"""
This type stub file was generated by pyright.
"""

from typing import Any
from asgiref.typing import ASGI3Application, ASGIReceiveCallable, ASGISendCallable, WWWScope

PLACEHOLDER_FORMAT = ...
def message_with_placeholders(message: Any) -> Any:
    """
    Return an ASGI message, with any body-type content omitted and replaced
    with a placeholder.
    """
    ...

class MessageLoggerMiddleware:
    def __init__(self, app: ASGI3Application) -> None:
        ...
    
    async def __call__(self, scope: WWWScope, receive: ASGIReceiveCallable, send: ASGISendCallable) -> None:
        ...
    


