"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Union
from asgiref.typing import ASGI3Application, ASGIReceiveCallable, ASGISendCallable, Scope

"""
This middleware can be used when a known proxy is fronting the application,
and is trusted to be properly setting the `X-Forwarded-Proto` and
`X-Forwarded-For` headers with the connecting client information.

Modifies the `client` and `scheme` information so that they reference
the connecting client, rather that the connecting proxy.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#Proxies
"""
class ProxyHeadersMiddleware:
    def __init__(self, app: ASGI3Application, trusted_hosts: Union[List[str], str] = ...) -> None:
        ...
    
    def get_trusted_client_host(self, x_forwarded_for_hosts: List[str]) -> Optional[str]:
        ...
    
    async def __call__(self, scope: Scope, receive: ASGIReceiveCallable, send: ASGISendCallable) -> None:
        ...
    


