"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Callable

STATUS_PHRASES = ...
class H11Protocol(asyncio.Protocol):
    def __init__(self, config, server_state, on_connection_lost: Callable = ..., _loop=...) -> None:
        ...
    
    def connection_made(self, transport): # -> None:
        ...
    
    def connection_lost(self, exc):
        ...
    
    def eof_received(self): # -> None:
        ...
    
    def data_received(self, data): # -> None:
        ...
    
    def handle_events(self): # -> None:
        ...
    
    def handle_upgrade(self, event):
        ...
    
    def on_response_complete(self): # -> None:
        ...
    
    def shutdown(self): # -> None:
        """
        Called by the server to commence a graceful shutdown.
        """
        ...
    
    def pause_writing(self): # -> None:
        """
        Called by the transport when the write buffer exceeds the high water mark.
        """
        ...
    
    def resume_writing(self): # -> None:
        """
        Called by the transport when the write buffer drops below the low water mark.
        """
        ...
    
    def timeout_keep_alive_handler(self): # -> None:
        """
        Called on a keep-alive connection if no new data is received after a short
        delay.
        """
        ...
    


class RequestResponseCycle:
    def __init__(self, scope, conn, transport, flow, logger, access_logger, access_log, default_headers, message_event, on_response) -> None:
        ...
    
    async def run_asgi(self, app):
        ...
    
    async def send_500_response(self): # -> None:
        ...
    
    async def send(self, message):
        ...
    
    async def receive(self): # -> dict[str, str] | dict[str, str | bytes | bool]:
        ...
    


