"""
This type stub file was generated by pyright.
"""

import typing
from uvicorn.supervisors.basereload import BaseReload
from uvicorn.supervisors.multiprocess import Multiprocess

if typing.TYPE_CHECKING:
    ChangeReload: typing.Type[BaseReload]
    ...
else:
    ...
__all__ = ["Multiprocess", "ChangeReload"]
