"""
This type stub file was generated by pyright.
"""

import os
from pathlib import Path
from socket import socket
from typing import Callable, List, Optional, TYPE_CHECKING
from watchgod import DefaultWatcher
from uvicorn.config import Config
from uvicorn.supervisors.basereload import BaseReload

logger = ...
if TYPE_CHECKING:
    DirEntry = os.DirEntry[str]
class CustomWatcher(DefaultWatcher):
    def __init__(self, root_path: Path, config: Config) -> None:
        ...
    
    def should_watch_file(self, entry: DirEntry) -> bool:
        ...
    
    def should_watch_dir(self, entry: DirEntry) -> bool:
        ...
    


class WatchGodReload(BaseReload):
    def __init__(self, config: Config, target: Callable[[Optional[List[socket]]], None], sockets: List[socket]) -> None:
        ...
    
    def should_restart(self) -> bool:
        ...
    


