"""
This type stub file was generated by pyright.
"""

import ssl
import typing
import click
from asgiref.typing import ASGIApplication
from uvicorn.config import SSL_PROTOCOL_VERSION

LEVEL_CHOICES = ...
HTTP_CHOICES = ...
WS_CHOICES = ...
LIFESPAN_CHOICES = ...
LOOP_CHOICES = ...
INTERFACE_CHOICES = ...
logger = ...
def print_version(ctx: click.Context, param: click.Parameter, value: bool) -> None:
    ...

@click.command()
@click.argument("app")
@click.option("--host", type=str, default="127.0.0.1", help="Bind socket to this host.", show_default=True)
@click.option("--port", type=int, default=8000, help="Bind socket to this port.", show_default=True)
@click.option("--uds", type=str, default=None, help="Bind to a UNIX domain socket.")
@click.option("--fd", type=int, default=None, help="Bind to socket from this file descriptor.")
@click.option("--debug", is_flag=True, default=False, help="Enable debug mode.", hidden=True)
@click.option("--reload", is_flag=True, default=False, help="Enable auto-reload.")
@click.option("--reload-dir", "reload_dirs", multiple=True, help="Set reload directories explicitly, instead of using the current working" " directory.", type=click.Path(exists=True))
@click.option("--reload-include", "reload_includes", multiple=True, help="Set glob patterns to include while watching for files. Includes '*.py' " "by default, which can be overridden in reload-excludes.")
@click.option("--reload-exclude", "reload_excludes", multiple=True, help="Set glob patterns to exclude while watching for files. Includes " "'.*, .py[cod], .sw.*, ~*' by default, which can be overridden in reload-excludes.")
@click.option("--reload-delay", type=float, default=0.25, show_default=True, help="Delay between previous and next check if application needs to be." " Defaults to 0.25s.")
@click.option("--workers", default=None, type=int, help="Number of worker processes. Defaults to the $WEB_CONCURRENCY environment" " variable if available, or 1. Not valid with --reload.")
@click.option("--loop", type=LOOP_CHOICES, default="auto", help="Event loop implementation.", show_default=True)
@click.option("--http", type=HTTP_CHOICES, default="auto", help="HTTP protocol implementation.", show_default=True)
@click.option("--ws", type=WS_CHOICES, default="auto", help="WebSocket protocol implementation.", show_default=True)
@click.option("--ws-max-size", type=int, default=16777216, help="WebSocket max size message in bytes", show_default=True)
@click.option("--ws-ping-interval", type=float, default=20, help="WebSocket ping interval", show_default=True)
@click.option("--ws-ping-timeout", type=float, default=20, help="WebSocket ping timeout", show_default=True)
@click.option("--lifespan", type=LIFESPAN_CHOICES, default="auto", help="Lifespan implementation.", show_default=True)
@click.option("--interface", type=INTERFACE_CHOICES, default="auto", help="Select ASGI3, ASGI2, or WSGI as the application interface.", show_default=True)
@click.option("--env-file", type=click.Path(exists=True), default=None, help="Environment configuration file.", show_default=True)
@click.option("--log-config", type=click.Path(exists=True), default=None, help="Logging configuration file. Supported formats: .ini, .json, .yaml.", show_default=True)
@click.option("--log-level", type=LEVEL_CHOICES, default=None, help="Log level. [default: info]", show_default=True)
@click.option("--access-log/--no-access-log", is_flag=True, default=True, help="Enable/Disable access log.")
@click.option("--use-colors/--no-use-colors", is_flag=True, default=None, help="Enable/Disable colorized logging.")
@click.option("--proxy-headers/--no-proxy-headers", is_flag=True, default=True, help="Enable/Disable X-Forwarded-Proto, X-Forwarded-For, X-Forwarded-Port to " "populate remote address info.")
@click.option("--server-header/--no-server-header", is_flag=True, default=True, help="Enable/Disable default Server header.")
@click.option("--date-header/--no-date-header", is_flag=True, default=True, help="Enable/Disable default Date header.")
@click.option("--forwarded-allow-ips", type=str, default=None, help="Comma seperated list of IPs to trust with proxy headers. Defaults to" " the $FORWARDED_ALLOW_IPS environment variable if available, or '127.0.0.1'.")
@click.option("--root-path", type=str, default="", help="Set the ASGI 'root_path' for applications submounted below a given URL path.")
@click.option("--limit-concurrency", type=int, default=None, help="Maximum number of concurrent connections or tasks to allow, before issuing" " HTTP 503 responses.")
@click.option("--backlog", type=int, default=2048, help="Maximum number of connections to hold in backlog")
@click.option("--limit-max-requests", type=int, default=None, help="Maximum number of requests to service before terminating the process.")
@click.option("--timeout-keep-alive", type=int, default=5, help="Close Keep-Alive connections if no new data is received within this timeout.", show_default=True)
@click.option("--ssl-keyfile", type=str, default=None, help="SSL key file", show_default=True)
@click.option("--ssl-certfile", type=str, default=None, help="SSL certificate file", show_default=True)
@click.option("--ssl-keyfile-password", type=str, default=None, help="SSL keyfile password", show_default=True)
@click.option("--ssl-version", type=int, default=SSL_PROTOCOL_VERSION, help="SSL version to use (see stdlib ssl module's)", show_default=True)
@click.option("--ssl-cert-reqs", type=int, default=ssl.CERT_NONE, help="Whether client certificate is required (see stdlib ssl module's)", show_default=True)
@click.option("--ssl-ca-certs", type=str, default=None, help="CA certificates file", show_default=True)
@click.option("--ssl-ciphers", type=str, default="TLSv1", help="Ciphers to use (see stdlib ssl module's)", show_default=True)
@click.option("--header", "headers", multiple=True, help="Specify custom default HTTP response headers as a Name:Value pair")
@click.option("--version", is_flag=True, callback=print_version, expose_value=False, is_eager=True, help="Display the uvicorn version and exit.")
@click.option("--app-dir", "app_dir", default=".", show_default=True, help="Look for APP in the specified directory, by adding this to the PYTHONPATH." " Defaults to the current working directory.")
@click.option("--factory", is_flag=True, default=False, help="Treat APP as an application factory, i.e. a () -> <ASGI app> callable.", show_default=True)
def main(app: str, host: str, port: int, uds: str, fd: int, loop: str, http: str, ws: str, ws_max_size: int, ws_ping_interval: float, ws_ping_timeout: float, lifespan: str, interface: str, debug: bool, reload: bool, reload_dirs: typing.List[str], reload_includes: typing.List[str], reload_excludes: typing.List[str], reload_delay: float, workers: int, env_file: str, log_config: str, log_level: str, access_log: bool, proxy_headers: bool, server_header: bool, date_header: bool, forwarded_allow_ips: str, root_path: str, limit_concurrency: int, backlog: int, limit_max_requests: int, timeout_keep_alive: int, ssl_keyfile: str, ssl_certfile: str, ssl_keyfile_password: str, ssl_version: int, ssl_cert_reqs: int, ssl_ca_certs: str, ssl_ciphers: str, headers: typing.List[str], use_colors: bool, app_dir: str, factory: bool) -> None:
    ...

def run(app: typing.Union[ASGIApplication, str], **kwargs: typing.Any) -> None:
    ...

if __name__ == "__main__":
    ...
