"""
This type stub file was generated by pyright.
"""

from typing import Any
from gunicorn.workers.base import Worker

class UvicornWorker(Worker):
    """
    A worker class for Gunicorn that interfaces with an ASGI consumer callable,
    rather than a WSGI callable.
    """
    CONFIG_KWARGS = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    
    def init_process(self) -> None:
        ...
    
    def init_signals(self) -> None:
        ...
    
    def run(self) -> None:
        ...
    
    async def callback_notify(self) -> None:
        ...
    


class UvicornH11Worker(UvicornWorker):
    CONFIG_KWARGS = ...


